"""
Guardion AI — Model Training Script
=====================================
Trains a Logistic Regression classifier on sentence embeddings from
the all-MiniLM-L6-v2 model (sentence-transformers).

Pipeline:
  1. Load CSV dataset (generated by dataset_generator.py)
  2. Encode prompts → 384-dim sentence embeddings
  3. Train sklearn LogisticRegression
  4. Evaluate on a held-out test split
  5. Save model.pkl and label_encoder.pkl

Training time: well under 1 minute on any modern machine.
"""

import os
import csv
import time
import numpy as np
import joblib

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
from sentence_transformers import SentenceTransformer

# ──────────────────── Constants ────────────────────

BASE_DIR = os.path.dirname(__file__)
DATA_PATH = os.path.join(BASE_DIR, "data", "training_data.csv")
MODEL_DIR = os.path.join(BASE_DIR, "model")
MODEL_PATH = os.path.join(MODEL_DIR, "model.pkl")
ENCODER_PATH = os.path.join(MODEL_DIR, "label_encoder.pkl")
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"


# ──────────────────── Data Loading ────────────────────

def load_dataset(csv_path: str) -> tuple[list[str], list[str]]:
    """
    Load prompt-label pairs from a CSV file.

    Returns:
        (prompts, labels) — two parallel lists of strings.
    """
    prompts, labels = [], []
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            prompts.append(row["prompt"])
            labels.append(row["label"])
    print(f"📂 Loaded {len(prompts)} examples from {csv_path}")
    return prompts, labels


# ──────────────────── Training ────────────────────

def train(csv_path: str = DATA_PATH) -> dict:
    """
    Full training pipeline.

    Steps:
      1. Load dataset from CSV
      2. Encode labels with LabelEncoder
      3. Generate sentence embeddings (all-MiniLM-L6-v2)
      4. Split into train/test (80/20)
      5. Train Logistic Regression
      6. Evaluate and print classification report
      7. Save model and label encoder to disk

    Returns:
        Dict with accuracy, classification_report, and model paths.
    """
    start = time.time()

    # Step 1: Load data
    prompts, labels = load_dataset(csv_path)

    # Step 2: Encode labels → integers
    label_encoder = LabelEncoder()
    y = label_encoder.fit_transform(labels)
    print(f"🏷️  Classes: {list(label_encoder.classes_)}")

    # Step 3: Generate sentence embeddings
    print(f"🔄 Loading embedding model: {EMBEDDING_MODEL_NAME}...")
    embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)
    print("🔄 Generating embeddings...")
    X = embedding_model.encode(prompts, show_progress_bar=True, batch_size=64)
    X = np.array(X)
    print(f"   Embedding shape: {X.shape}")  # (N, 384)

    # Step 4: Train / test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print(f"📊 Train: {len(X_train)}, Test: {len(X_test)}")

    # Step 5: Train Logistic Regression classifier
    print("🏋️  Training Logistic Regression...")
    classifier = LogisticRegression(
        max_iter=1000,
        C=1.0,                  # Regularization strength
        solver="lbfgs",         # Robust solver for multiclass
        random_state=42,
    )
    classifier.fit(X_train, y_train)

    # Step 6: Evaluate
    y_pred = classifier.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(
        y_test, y_pred,
        target_names=label_encoder.classes_,
        digits=3,
    )
    print(f"\n✅ Accuracy: {accuracy:.4f}")
    print(f"\n📋 Classification Report:\n{report}")

    # Step 7: Save model artifacts
    os.makedirs(MODEL_DIR, exist_ok=True)
    joblib.dump(classifier, MODEL_PATH)
    joblib.dump(label_encoder, ENCODER_PATH)
    print(f"\n💾 Model saved:         {MODEL_PATH}")
    print(f"💾 Label encoder saved: {ENCODER_PATH}")

    elapsed = time.time() - start
    print(f"\n⏱️  Total training time: {elapsed:.1f}s")

    return {
        "accuracy": accuracy,
        "report": report,
        "model_path": MODEL_PATH,
        "encoder_path": ENCODER_PATH,
        "training_time_seconds": round(elapsed, 1),
    }


# ──────────────────── CLI Entry Point ────────────────────

if __name__ == "__main__":
    # Generate dataset first if it doesn't exist
    if not os.path.exists(DATA_PATH):
        print("⚠️  Dataset not found — generating it first...\n")
        from guardion_ai_model.dataset_generator import generate_dataset
        generate_dataset(DATA_PATH)
        print()

    # Train
    results = train()
    print(f"\n🎯 Final accuracy: {results['accuracy']:.2%}")

    